@startuml
left to right direction
actor "Gestionnaire" as gestionnaire
actor "Client" as Client
rectangle "Utilisateur" {
    (Créer un groupe) as créer
    (lister les groupes) as lister
    (rejoindre un groupe par mot de passe) as rejoindre
    (quitter un groupe) as quitter
    (écrire un message) as écrire
    (Lire les messages) as lire
    (Lister les membres) as membres
}
rectangle "Administrateur"{
    (supprimer un groupe) as supprimer_groupe
    (fusionner 2 groupes) as fusionner
    (Moderer un membre) as moderer
}
Client -- créer
Client -- lister
Client -- rejoindre
Client -- quitter
Client -- écrire
Client -- lire
Client -- membres
gestionnaire -- supprimer_groupe
gestionnaire -- fusionner
gestionnaire -- moderer
gestionnaire --> Client
@enduml