@startuml
left to right direction
actor "Gestionnaire" as gestionnaire
actor "Client" as Client
rectangle "Utilisateur" {
    (Créer un groupe) as créer
    (lister les groupes) as lister
    (Rejoindre un groupe par mot de passe) as rejoindre
    (Quitter un groupe) as quitter
    (Ecrire un message) as écrire
    (Lire les messages) as lire
    (Lister les membres) as membres
    (Gain de points pour fonctionnalitées supplémentaire) as banque
}
rectangle "Administrateur"{
    (supprimer un groupe) as supprimer_groupe
    (fusionner 2 groupes) as fusionner
    (Moderer un membre) as moderer
    (Ajouter points à un client) as ajouter
}
Client -- créer
Client -- lister
Client -- rejoindre
Client -- quitter
Client -- écrire
Client -- lire
Client -- membres
Client -- banque
gestionnaire -- supprimer_groupe
gestionnaire -- fusionner
gestionnaire -- moderer
gestionnaire --> Client
gestionnaire -- ajouter
@enduml
